version: '3.0'

services: 
  auth-db:
    image: postgres
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432   
    
  product-db:
    image: postgres
    container_name: product-db
    restart: always
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - 5435:5432    

  sales-db:
    image: tutum/mongodb
    container_name: sales-db
    restart: always
    environment:
      MONGODB_DATABASE: sales
      MONGODB_USER: admin
      MONGODB_PASS: 123456
    ports:
      - 27017:27017
      - 28017:28017   

  sales_rabbit:
    image: rabbitmq:3.8.3-management
    container_name: sales_rabbit         
    ports:
      - 5672:5762 
      - 25676:25676 
      - 15672:15672                             
            